apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: personal-site
  app.kubernetes.io/component: frontend

# Image to use
images:
  - name: ghcr.io/yourusername/personal-site
    newTag: latest

# ConfigMap generator for environment-specific configs
# configMapGenerator:
#   - name: site-config
#     literals:
#       - ENVIRONMENT=production
